### ISSUE TITLE
Why all the header clobbering?

### ISSUE THREAD

**Issue by stringfellow** [samgiles/slumber#50]
In the get, put, post, patch methods, the only thing that is returned is the content. What about the headers?

Some APIs respond with info in the headers rather than the body, so this is all lost.

**Comment by samgiles** [comment]
Taken a while I know, but on master you can now initialise the API like: 

`slumber.API(base_uri, raw=True)`

Then every return value from an HTTP operation will be a tuple `(response, decoded)`, where response is the raw `requests.Response`, and `decoded` is the decoded content body if a body exists, `None` otherwise.

This can also be done on a per request basis, by calling `as_raw` on a resource before calling the http operation:

`(response, decoded) = api.myresource.as_raw().get()`

This will get put into a new major release I'm shooting for a `1.0` soon.
